import React from "react";
import { Link } from "react-router";
import boilerFeedHeroImage from "../../assets/images/bolier feed water.jpg";
import boilerFeedGenerated from "../../assets/images/generated/boiler-feed-water-treatment.png";
import mixedBedSupportImage from "../../assets/images/generated/mixed-bed-condensate-polishing.png";

const faqs = [["Which resins treat boiler feed water?", "Softening (AGRION C-80 / C-60) and dealkalisation (AGRION WC-50) for the make-up, two-bed demineralisation (AGRION C-100 H + A-400) for higher-pressure boilers, and a mixed bed (AGRION MB-1151) for condensate polishing."], ["Why remove alkalinity from boiler feed water?", "Bicarbonate alkalinity breaks down to CO₂ in the boiler, releasing carbon dioxide that corrodes the condensate lines. A weak acid cation resin (AGRION WC-50) removes it, and also cuts regenerant cost on the downstream demineraliser."], ["Do I need demineralisation, or is softening enough?", "Low-pressure boilers may run on softened, dealkalised make-up. Higher-pressure boilers need demineralised feed water — residual dissolved solids and silica cause scale and turbine deposits at pressure. Share your boiler pressure and we’ll advise the right train."], ["Which resin removes silica for high-pressure boilers?", "A Type 1 strong base anion resin such as AGRION A-400 — Type 1 chemistry gives the high silica and CO₂ removal that high-pressure boiler feed water needs to protect turbine blades."], ["Do you supply resin for condensate polishing?", "Yes — the AGRION MB-1151 mixed bed polishes returning condensate to very low conductivity, removing corrosion products and dissolved ions before they re-enter the boiler."], ["How do I know when to replace boiler feed water resin?", "Rising treated-water conductivity, hardness or silica leakage, shorter runs between regenerations, or higher regenerant use all point to exhaustion or degradation. Share your trends and we’ll advise whether a change is due."], ["Can AGRION resins replace the ones we run today?", "In most cases, yes. Match on resin type, ionic form, capacity and bead size and an AGRION grade drops into the same vessel. Send us your current grades or datasheets and we’ll confirm the equivalents."]];
const stages = [{"n": "1", "duty": "Stage 1", "title": "Soften & dealkalise the make-up", "tag": "The grade", "text": "Sodium-cycle softening removes calcium and magnesium to stop scale; a weak acid cation resin removes bicarbonate alkalinity, cutting boiler CO₂ and condensate-line corrosion.", "items": [{"text": "AGRION C-80", "href": null}, {"text": "AGRION WC-50", "href": null}, {"text": "Water softener resins", "href": "/products/water-softener-resins"}]}, {"n": "2", "duty": "Stage 2", "title": "Demineralise for higher-pressure boilers", "tag": "The grade", "text": "Two-bed demineralisation strips dissolved salts and silica — critical for high-pressure boilers where silica carry-over damages turbine blades.", "items": [{"text": "AGRION C-100 H", "href": null}, {"text": "AGRION A-400", "href": null}, {"text": "DM plant", "href": "/applications/dm-plant-resin"}]}, {"n": "3", "duty": "Stage 3", "title": "Polish the returning condensate", "tag": "The grade", "text": "A mixed bed polishes returning condensate to very low conductivity, removing corrosion products and dissolved ions before they reach the boiler — protecting the steam cycle.", "items": [{"text": "AGRION MB-1151", "href": null}, {"text": "Mixed bed resins", "href": "/products/mixed-bed-resins"}]}];

function ImagePlaceholder({ second = false }) {
  return (
    <figure className="my-8 overflow-hidden border border-[#C8DCEC] bg-[#F7FAFD] shadow-sm">
      <img
        src={second ? mixedBedSupportImage : boilerFeedGenerated}
        alt={second ? "Condensate polishing stage supporting the boiler feed water treatment train" : "Boiler feed water treatment system with softener, dealkaliser, DM and mixed-bed polishing"}
        loading="lazy"
        className="block w-full aspect-[16/9] object-cover object-center"
      />
    </figure>
  );
}

export default function BoilerFeedWater() {
 return <div className="min-h-screen bg-white text-slate-800 font-sans overflow-x-hidden">
  <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap');
  .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'IBM Plex Mono',monospace} body{font-family:'Inter',sans-serif}
  .blueprint{background-image:linear-gradient(rgba(24,104,168,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(24,104,168,.06) 1px,transparent 1px);background-size:32px 32px}
  @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @media(prefers-reduced-motion:reduce){.client-track{animation:none;flex-wrap:wrap;justify-content:center;width:auto}}
  `}</style>
  <main>
   <section className="blueprint relative border-b border-[#C8DCEC] bg-[#F7FAFD]" style={{backgroundImage: `linear-gradient(90deg, rgba(247,250,253,.92) 0%, rgba(247,250,253,.84) 30%, rgba(247,250,253,.62) 50%, rgba(247,250,253,.30) 70%, rgba(247,250,253,.10) 100%), linear-gradient(180deg, rgba(247,250,253,.04) 0%, rgba(247,250,253,.14) 100%), url(${boilerFeedHeroImage})`, backgroundSize: "cover", backgroundPosition: "center center", backgroundRepeat: "no-repeat"}}><div className="max-w-[1160px] mx-auto px-6 py-8 sm:py-10 lg:py-14">
    <p className="font-mono text-xs text-slate-500 mb-7"><Link to="/">Home</Link><span className="mx-2">›</span><Link to="/applications">Applications</Link><span className="mx-2">›</span><b className="text-[#0A2C4B]">Boiler Feed Water</b></p>
    <div className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[.18em] text-[#B27B34] font-semibold">// Applications — Boiler Feed Water</p><h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[#0A2C4B] leading-[1.05] mt-5">Boiler feed water treatment <em className="text-[#1868A8]">resin</em></h1><p className="mt-6 max-w-3xl text-base sm:text-lg text-slate-600 leading-relaxed">The ion exchange resins that soften, dealkalise, demineralise and polish boiler feed water — protecting boilers and turbines from scale and corrosion.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/contact" className="bg-[#1868A8] text-white px-6 py-3 font-semibold text-sm hover:bg-[#0A2C4B] transition">Enquire now</Link><Link to="/products" className="border border-[#0A2C4B] text-[#0A2C4B] bg-white px-6 py-3 font-semibold text-sm hover:bg-[#EFF6FC] transition">View our resins</Link></div><div className="flex flex-wrap gap-2 mt-7">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[11px] text-[#0A2C4B] border border-[#C8DCEC] bg-white px-3 py-2">{x}</span>)}</div></div>
   </div></section>
   <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10 lg:gap-12 items-start"><div className="min-w-0">
    <section className="pb-10"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why boiler feed water treatment resin matters</h2><div className="mt-5 text-slate-600 leading-relaxed space-y-4"><p>Boiler feed water is a blend of returning condensate and make-up water. If hardness, alkalinity, dissolved salts, silica or organics reach the boiler, they cause scale, corrosion and carry-over — cutting efficiency and forcing outages.</p><p>Ion exchange does the heavy lifting: softening and dealkalising the make-up, demineralising for higher-pressure boilers, and polishing the returning condensate. Toyota Chemical Industries supplies every grade in that train, each with a technical data sheet.</p></div></section>
    <ImagePlaceholder />
    <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries boiler feed water treatment resin, stage by stage</h2><p className="mt-4 text-slate-600">Each stage is built from a specific AGRION grade, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
    <ImagePlaceholder second />
    <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Boiler feed water treatment resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section>
   </div>
   <aside className="lg:sticky lg:top-24 space-y-5"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">Boiler feed resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your boiler pressure and feedwater analysis — we’ll recommend the softening, DM and polishing grades and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
   {[["Resins for this application",[["Water Softener Resins","/products/water-softener-resins"],["Cation Exchange Resins","/products/cation-exchange-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"],["Mixed Bed Resins","/products/mixed-bed-resins"]]],["Related applications",[["DM Plant / Demineralisation","/applications/dm-plant-resin"],["Dealkalisation","/applications/dealkalisation-resin"],["Water Softening","/applications/water-softener-resin"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
   </aside></div>
   <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Protect your boilers with Toyota Chemical Industries feed-water resins.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your boiler pressure and feedwater analysis and we’ll recommend the grades and attach their TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
   
  </main>
 </div>;
}
