// import React from "react";

// const faqs = [["What does a dealkalisation resin do?", "It removes the hardness associated with bicarbonate alkalinity. A weak acid cation resin (AGRION WC-50) in the hydrogen form converts that alkalinity to carbonic acid, which is then stripped as CO₂ — lowering feedwater alkalinity before softening or demineralisation."], ["Why is alkalinity a problem for boilers?", "Bicarbonate alkalinity breaks down in the boiler to release carbon dioxide, which dissolves in the condensate and corrodes return lines. Removing it upstream protects the condensate system and improves cycle life."], ["Does dealkalisation reduce my regenerant cost?", "Yes. Run ahead of a demineraliser, a weak acid cation stage removes alkalinity-linked hardness at very high regeneration efficiency, cutting the acid demand on the downstream strong acid cation bed."], ["What is the difference between softening and dealkalisation?", "Softening (sodium cycle) swaps hardness for sodium but leaves alkalinity in the water. Dealkalisation (weak acid cation, hydrogen cycle) removes the alkalinity-linked hardness and, after degassing, lowers total dissolved solids as well. They are often used together."], ["Which AGRION grade is used for dealkalisation?", "AGRION WC-50, a weak acid cation resin with carboxylic acid groups. It is used in the hydrogen form ahead of a softener or the strong-acid stage of a DM plant."], ["Do I need a degasser after the dealkaliser?", "Usually, yes. The dealkaliser converts alkalinity to carbonic acid; a degasser (or vacuum degasser) then strips the CO₂ so it doesn’t reach the boiler or load the downstream anion resin."], ["Can AGRION WC-50 replace the resin we run today?", "In most cases, yes. Match on functional type (weak acid cation), form, capacity and bead size and it drops into the same vessel. Send us your current grade or datasheet and we’ll confirm the equivalent."]];
// const stages = [{"n": "1", "duty": "Stage 1", "title": "Remove alkalinity-linked hardness", "tag": "The grade", "text": "A weak acid cation resin in the hydrogen form exchanges the calcium and magnesium associated with bicarbonate alkalinity for H⁺, converting alkalinity to carbonic acid — with very high regeneration efficiency.", "items": [{"text": "AGRION WC-50"}, {"text": "Cation exchange resins", "href": "/products/cation-exchange-resins"}]}, {"n": "2", "duty": "Stage 2", "title": "Degas the carbon dioxide", "tag": "The step", "text": "The carbonic acid formed is stripped as CO₂ in a degasser, so it never reaches the boiler or loads the downstream anion resin. This is a process step — no resin — but it’s where dealkalisation pays off.", "items": [{"text": "Degasser"}, {"text": "CO₂ removal"}]}, {"n": "+", "duty": "Then", "title": "Soften or demineralise the balance", "tag": "The grade", "text": "After dealkalisation, a sodium-cycle softener finishes the make-up, or a strong acid cation + strong base anion train demineralises it — now with lower acid demand and lower CO₂ load.", "items": [{"text": "AGRION C-80"}, {"text": "Water softening", "href": "/applications/water-softener-resin"}, {"text": "DM plant", "href": "/applications/dm-plant-resin"}]}];

// function ImagePlaceholder({ second=false }) {
//  const data = second ? {title:"Close-up of WC-50 resin beads / dealkalisation diagram",desc:"A product-level visual to break up the FAQ and reinforce the grade.",prompt:"A crisp macro of amber weak-acid-cation resin beads in a gloved hand or lab dish with soft bokeh — or a simple labelled diagram of the dealkalisation flow (raw water → weak acid cation (H form) → degasser → softener / DM) in the navy/green brand palette. Clean, technical, landscape 16:9."} : {title:"Dealkalisation / softening pressure vessels in a plant",desc:"A wide industrial shot that sets the context for the page.",prompt:"A clean industrial water-treatment room showing weak-acid-cation and softener pressure vessels (FRP or steel) with piping, brine/acid regeneration lines and control valves; blue-and-steel palette, professional documentary style, no people, landscape 16:9. Optional light AGRION / Toyota Chemical Industries branding on the vessels."};
//  return <div className="my-2 flex flex-col sm:flex-row gap-5 items-start border-2 border-dashed border-[#C8DCEC] bg-[#F6F9FC] p-7 sm:p-8"><div className="shrink-0 w-14 h-14 bg-[#06182B] text-white grid place-items-center text-2xl">▧</div><div><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">Image to add</span><h4 className="font-serif text-xl font-bold text-[#0A2C4B] mt-2">{data.title}</h4><p className="text-sm text-slate-600 mt-1">{data.desc}</p><p className="mt-3 text-xs italic text-slate-500 bg-white border border-[#C8DCEC] p-3"><b className="not-italic text-[#0A2C4B]">Prompt:</b> {data.prompt}</p></div></div>;
// }

// export default function DealkalisationResin() {
//  return <div className="min-h-screen bg-white text-slate-800 [font-family:Inter,Arial,sans-serif] pb-16 lg:pb-0">
//   <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500;600&display=swap'); .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'JetBrains Mono',monospace} .blueprint-dark{background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:28px 28px} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} @media(prefers-reduced-motion:reduce){.client-track{animation:none}}`}</style>
//   <main id="main">
//    <section className="relative overflow-hidden bg-[#06182B] text-white blueprint-dark"><div className="absolute inset-y-0 right-0 w-1/3 bg-gradient-to-l from-[#1868A8]/30 to-transparent"/><div className="relative max-w-[1160px] mx-auto px-6 py-16 sm:py-20 text-center"><p className="font-mono text-xs text-slate-300">Home › Applications › Dealkalisation</p><p className="font-mono text-xs uppercase tracking-[.22em] text-[#E5A855] font-semibold mt-6">// Applications — Dealkalisation</p><h1 className="font-serif text-5xl sm:text-6xl font-semibold mt-4">Dealkalisation resin</h1><p className="max-w-3xl mx-auto text-slate-300 text-lg mt-5">The weak acid cation resin that removes alkalinity-linked hardness — cutting boiler CO₂, protecting condensate lines and reducing regenerant cost.</p><div className="flex gap-3 justify-center flex-wrap mt-8"><Link className="bg-[#B27B34] px-6 py-3 font-semibold" to="/contact">Enquire now</Link><Link className="border border-white/40 px-6 py-3 font-semibold" to="/products">View our resins</Link></div><div className="flex flex-wrap justify-center gap-2 mt-8">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[10px] uppercase tracking-wider border border-white/20 px-3 py-2">{x}</span>)}</div></div></section>
//    <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10">
//     <div><section className="py-8"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why dealkalisation resin matters</h2><div className="mt-5 space-y-4 text-slate-600 leading-relaxed"><p>Alkalinity in feedwater — mostly bicarbonate — is more than a hardness problem. In a boiler it breaks down to carbon dioxide, which corrodes the condensate lines; ahead of a demineraliser it drives up acid consumption. Dealkalisation removes that alkalinity-linked hardness before it becomes a cost.</p><p>The workhorse is a weak acid cation resin, run in the hydrogen form ahead of a softener or the strong-acid bed of a DM plant. Toyota Chemical Industries supplies the grade for that duty, with a technical data sheet.</p></div></section>
//     <ImagePlaceholder />
//     <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries dealkalisation resin, stage by stage</h2><p className="mt-4 text-slate-600">How weak acid cation dealkalisation fits your train — built from a specific AGRION grade, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
//     <ImagePlaceholder second />
//     <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Dealkalisation resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section></div>
//     <aside className="lg:sticky lg:top-24 space-y-5 self-start"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">Dealkalisation resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your feedwater alkalinity and duty — we’ll confirm the weak acid cation grade and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
//     {[["Resins for this application",[["Cation Exchange Resins","/products/cation-exchange-resins"],["Water Softener Resins","/products/water-softener-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"]]],["Related applications",[["DM Plant / Demineralisation","/applications/dm-plant-resin"],["Water Softening","/applications/water-softener-resin"],["Boiler Feed Water","/applications/boiler-feed-water-treatment"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
//     </aside></div>
//    <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Cut alkalinity and regenerant cost with Toyota Chemical Industries dealkalisation resin.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your feedwater alkalinity and duty and we’ll confirm the grade and attach its TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
//    
//    <div className="lg:hidden fixed bottom-0 inset-x-0 z-50 bg-white border-t border-[#C8DCEC] p-2 grid grid-cols-3 gap-2"><a className="text-center border border-[#0A2C4B] text-[#0A2C4B] py-2.5 text-sm font-semibold" href="tel:+912602432021">Call</a><a className="text-center bg-[#B27B34] text-white py-2.5 text-sm font-semibold" href="https://wa.me/919898701010">WhatsApp</a><Link className="text-center bg-[#1868A8] text-white py-2.5 text-sm font-semibold" to="/contact">Enquire</Link></div>
//   </main>
//  </div>;
// }

import React from "react";
import { Link } from "react-router";

const faqs = [["What does a dealkalisation resin do?", "It removes the hardness associated with bicarbonate alkalinity. A weak acid cation resin (AGRION WC-50) in the hydrogen form converts that alkalinity to carbonic acid, which is then stripped as CO₂ — lowering feedwater alkalinity before softening or demineralisation."], ["Why is alkalinity a problem for boilers?", "Bicarbonate alkalinity breaks down in the boiler to release carbon dioxide, which dissolves in the condensate and corrodes return lines. Removing it upstream protects the condensate system and improves cycle life."], ["Does dealkalisation reduce my regenerant cost?", "Yes. Run ahead of a demineraliser, a weak acid cation stage removes alkalinity-linked hardness at very high regeneration efficiency, cutting the acid demand on the downstream strong acid cation bed."], ["What is the difference between softening and dealkalisation?", "Softening (sodium cycle) swaps hardness for sodium but leaves alkalinity in the water. Dealkalisation (weak acid cation, hydrogen cycle) removes the alkalinity-linked hardness and, after degassing, lowers total dissolved solids as well. They are often used together."], ["Which AGRION grade is used for dealkalisation?", "AGRION WC-50, a weak acid cation resin with carboxylic acid groups. It is used in the hydrogen form ahead of a softener or the strong-acid stage of a DM plant."], ["Do I need a degasser after the dealkaliser?", "Usually, yes. The dealkaliser converts alkalinity to carbonic acid; a degasser (or vacuum degasser) then strips the CO₂ so it doesn’t reach the boiler or load the downstream anion resin."], ["Can AGRION WC-50 replace the resin we run today?", "In most cases, yes. Match on functional type (weak acid cation), form, capacity and bead size and it drops into the same vessel. Send us your current grade or datasheet and we’ll confirm the equivalent."]];
const stages = [{"n": "1", "duty": "Stage 1", "title": "Remove alkalinity-linked hardness", "tag": "The grade", "text": "A weak acid cation resin in the hydrogen form exchanges the calcium and magnesium associated with bicarbonate alkalinity for H⁺, converting alkalinity to carbonic acid — with very high regeneration efficiency.", "items": [{"text": "AGRION WC-50"}, {"text": "Cation exchange resins", "href": "/products/cation-exchange-resins"}]}, {"n": "2", "duty": "Stage 2", "title": "Degas the carbon dioxide", "tag": "The step", "text": "The carbonic acid formed is stripped as CO₂ in a degasser, so it never reaches the boiler or loads the downstream anion resin. This is a process step — no resin — but it’s where dealkalisation pays off.", "items": [{"text": "Degasser"}, {"text": "CO₂ removal"}]}, {"n": "+", "duty": "Then", "title": "Soften or demineralise the balance", "tag": "The grade", "text": "After dealkalisation, a sodium-cycle softener finishes the make-up, or a strong acid cation + strong base anion train demineralises it — now with lower acid demand and lower CO₂ load.", "items": [{"text": "AGRION C-80"}, {"text": "Water softening", "href": "/applications/water-softener-resin"}, {"text": "DM plant", "href": "/applications/dm-plant-resin"}]}];
function ImagePlaceholder({ second=false }) {
 const data = second ? {title:"Close-up of WC-50 resin beads / dealkalisation diagram",desc:"A product-level visual to break up the FAQ and reinforce the grade.",prompt:"A crisp macro of amber weak-acid-cation resin beads in a gloved hand or lab dish with soft bokeh — or a simple labelled diagram of the dealkalisation flow (raw water → weak acid cation (H form) → degasser → softener / DM) in the navy/green brand palette. Clean, technical, landscape 16:9."} : {title:"Dealkalisation / softening pressure vessels in a plant",desc:"A wide industrial shot that sets the context for the page.",prompt:"A clean industrial water-treatment room showing weak-acid-cation and softener pressure vessels (FRP or steel) with piping, brine/acid regeneration lines and control valves; blue-and-steel palette, professional documentary style, no people, landscape 16:9. Optional light AGRION / Toyota Chemical Industries branding on the vessels."};
 return <div className="relative border-2 border-dashed border-[#C8DCEC] bg-gradient-to-br from-[#F7FAFD] to-[#EFF6FC] p-6 sm:p-8 flex flex-col sm:flex-row gap-5 items-start my-8"><div className="w-14 h-14 shrink-0 bg-[#0A2C4B] text-white grid place-items-center text-2xl shadow-lg">📷</div><div><span className="inline-block font-mono text-[10px] uppercase tracking-[.16em] font-bold text-[#B27B34] bg-[#F4E7D2] px-3 py-1">Image to add</span><h4 className="font-serif text-xl font-bold text-[#0A2C4B] mt-2">{data.title}</h4><p className="text-slate-600 text-sm mt-2">{data.desc}</p><p className="text-xs sm:text-sm text-slate-500 italic bg-white border border-[#C8DCEC] p-3 mt-3"><b className="not-italic text-[#0A2C4B]">Prompt:</b> {data.prompt}</p></div></div>;
}

export default function DealkalisationResin() {
 return <div className="min-h-screen bg-white text-slate-800 font-sans overflow-x-hidden">
  <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap'); .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'IBM Plex Mono',monospace} body{font-family:'Inter',sans-serif} .blueprint{background-image:linear-gradient(rgba(24,104,168,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(24,104,168,.06) 1px,transparent 1px);background-size:32px 32px} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} @media(prefers-reduced-motion:reduce){.client-track{animation:none}}`}</style>
  <main id="main">
   <section className="blueprint relative border-b border-[#C8DCEC] bg-[#F7FAFD]"><div className="max-w-[1160px] mx-auto px-6 py-8 sm:py-10 lg:py-14"><p className="font-mono text-xs text-slate-500 mb-7"><Link to="/">Home</Link><span className="mx-2">›</span><Link to="/applications">Applications</Link><span className="mx-2">›</span><b className="text-[#0A2C4B]">Dealkalisation</b></p><div className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[.18em] text-[#B27B34] font-semibold">// Applications — Dealkalisation</p><h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[#0A2C4B] leading-[1.05] mt-5">Dealkalisation <em className="text-[#1868A8]">resin</em></h1><p className="mt-6 max-w-3xl text-base sm:text-lg text-slate-600 leading-relaxed">The weak acid cation resin that removes alkalinity-linked hardness — cutting boiler CO₂, protecting condensate lines and reducing regenerant cost.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/contact" className="bg-[#1868A8] text-white px-6 py-3 font-semibold text-sm hover:bg-[#0A2C4B] transition">Enquire now</Link><Link to="/products" className="border border-[#0A2C4B] text-[#0A2C4B] bg-white px-6 py-3 font-semibold text-sm hover:bg-[#EFF6FC] transition">View our resins</Link></div><div className="flex flex-wrap gap-2 mt-7">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[11px] text-[#0A2C4B] border border-[#C8DCEC] bg-white px-3 py-2">{x}</span>)}</div></div></div></section>
   <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10 lg:gap-12 items-start">
    <div className="min-w-0"><section className="pb-10"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why dealkalisation resin matters</h2><div className="mt-5 space-y-4 text-slate-600 leading-relaxed"><p>Alkalinity in feedwater — mostly bicarbonate — is more than a hardness problem. In a boiler it breaks down to carbon dioxide, which corrodes the condensate lines; ahead of a demineraliser it drives up acid consumption. Dealkalisation removes that alkalinity-linked hardness before it becomes a cost.</p><p>The workhorse is a weak acid cation resin, run in the hydrogen form ahead of a softener or the strong-acid bed of a DM plant. Toyota Chemical Industries supplies the grade for that duty, with a technical data sheet.</p></div></section>
    <ImagePlaceholder />
    <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries dealkalisation resin, stage by stage</h2><p className="mt-4 text-slate-600">How weak acid cation dealkalisation fits your train — built from a specific AGRION grade, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
    <ImagePlaceholder second />
    <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Dealkalisation resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section></div>
    <aside className="lg:sticky lg:top-24 space-y-5"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">Dealkalisation resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your feedwater alkalinity and duty — we’ll confirm the weak acid cation grade and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
    {[["Resins for this application",[["Cation Exchange Resins","/products/cation-exchange-resins"],["Water Softener Resins","/products/water-softener-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"]]],["Related applications",[["DM Plant / Demineralisation","/applications/dm-plant-resin"],["Water Softening","/applications/water-softener-resin"],["Boiler Feed Water","/applications/boiler-feed-water-treatment"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
    </aside></div>
   <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Cut alkalinity and regenerant cost with Toyota Chemical Industries dealkalisation resin.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your feedwater alkalinity and duty and we’ll confirm the grade and attach its TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
   

  </main>
 </div>;
}
