// import React from "react";

// const faqs = [["Which resins are used in a DM plant?", "A strong acid cation resin (AGRION C-100 H) for the cation stage, a Type 1 strong base anion resin (AGRION A-400) for the anion stage, and a mixed bed (AGRION MB-1151) for polishing. High-alkalinity feedwater may add a weak acid cation stage (AGRION WC-50)."], ["What is the difference between two-bed and mixed-bed demineralisation?", "A two-bed system (separate cation then anion) removes the bulk of dissolved ions; a mixed bed polishes that output to much lower conductivity and silica. High-purity duties use two-bed followed by a mixed bed."], ["Which anion resin removes silica in a DM plant?", "A Type 1 strong base anion resin such as AGRION A-400 — Type 1 chemistry gives the high silica and CO₂ removal that boiler-feed demineralisation needs."], ["How does dealkalisation cut my regenerant cost?", "On high-alkalinity feedwater, a weak acid cation resin (AGRION WC-50) ahead of the strong-acid bed removes alkalinity-linked hardness at high regeneration efficiency, reducing the acid demand on the downstream cation resin."], ["How do I know when to replace DM plant resin?", "Rising treated-water conductivity, earlier silica breakthrough, shorter runs between regenerations or higher regenerant use all point to exhaustion or degradation. Share your trends and we’ll advise whether a change is due."], ["Do you supply the full DM resin set from one source?", "Yes — cation, anion, mixed bed and weak acid cation grades, all manufactured by Toyota Chemical Industries, from 25 litres to bulk, each with its TDS."], ["Can AGRION DM resins replace the ones I run today?", "In most cases, yes. Match on resin type, ionic form, capacity and bead size and an AGRION grade drops into the same vessel. Send us your current grades or datasheets and we’ll confirm the equivalents."]];
// const stages = [{"n": "1", "duty": "Stage 1 — Cation", "title": "Remove the cations", "tag": "The grade", "text": "A strong acid cation resin in the hydrogen form exchanges calcium, magnesium and sodium for H⁺, leaving the water acidic and cation-free.", "items": [{"text": "AGRION C-100 H"}, {"text": "Cation exchange resins", "href": "/products/cation-exchange-resins"}]}, {"n": "2", "duty": "Stage 2 — Anion", "title": "Remove the anions & silica", "tag": "The grade", "text": "A Type 1 strong base anion resin in the hydroxide form removes chloride, sulphate, silica and CO₂, neutralising the acidity and giving low-conductivity demineralised water.", "items": [{"text": "AGRION A-400"}, {"text": "Anion exchange resins", "href": "/products/anion-exchange-resins"}]}, {"n": "3", "duty": "Stage 3 — Polishing", "title": "Polish to high purity", "tag": "The grade", "text": "A mixed bed of cation and anion resin polishes the two-bed output to very low conductivity and high resistivity — for boiler feed, ultrapure and high-purity process water.", "items": [{"text": "AGRION MB-1151"}, {"text": "Mixed bed resins", "href": "/products/mixed-bed-resins"}]}, {"n": "+", "duty": "Optional — Pre-treatment", "title": "Cut regenerant cost on high-alkalinity water", "tag": "The grade", "text": "Where feedwater is high in alkalinity, a weak acid cation resin ahead of the strong-acid bed removes alkalinity-linked hardness first, cutting acid consumption and improving efficiency.", "items": [{"text": "AGRION WC-50"}, {"text": "Dealkalisation", "href": "/applications/dealkalisation-resin"}]}];

// function ImagePlaceholder({ second = false }) {
//  const data = second ? {title:"Close-up of cation + anion resin beads / DM flow diagram",desc:"A product-level visual to break up the FAQ and reinforce the grades.",prompt:"A crisp macro of amber cation and blue anion ion-exchange resin beads in a gloved hand or lab dish with soft bokeh — or a simple labelled diagram of the DM flow (raw water → cation (H) → anion (OH) → mixed-bed polishing → demineralised water) in the navy/green brand palette. Clean, technical, landscape 16:9."} : {title:"DM plant — two-bed + mixed bed pressure vessels",desc:"A wide industrial shot that sets the context for the page.",prompt:"A clean industrial demineralisation plant showing cation, anion and mixed-bed pressure vessels in a row with piping, acid/caustic regeneration lines and conductivity instrumentation; blue-and-steel palette, professional documentary style, no people, landscape 16:9. Optional light AGRION / Toyota Chemical Industries branding on the vessels."};
//  return <div className="my-8 border-2 border-dashed border-[#B8D1E4] bg-[#F6F9FC] p-6 sm:p-8 flex flex-col sm:flex-row gap-5 items-start"><div className="w-14 h-14 shrink-0 bg-[#0A2C4B] text-white grid place-items-center text-2xl">▣</div><div><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">Image to add</span><h4 className="font-serif text-xl font-bold text-[#0A2C4B] mt-2">{data.title}</h4><p className="text-sm text-slate-600 mt-1">{data.desc}</p><p className="mt-3 text-xs italic text-slate-500 bg-white border border-[#C8DCEC] p-3"><b className="not-italic text-[#0A2C4B]">Prompt:</b> {data.prompt}</p></div></div>;
// }

// export default function DMPlantResin() {
//  return <div className="min-h-screen bg-white text-slate-800 [font-family:Inter,Arial,sans-serif] pb-16 lg:pb-0">
//   <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500;600&display=swap'); .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'JetBrains Mono',monospace} .blueprint-dark{background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:28px 28px} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} @media(prefers-reduced-motion:reduce){.client-track{animation:none}}`}</style>
//   <main id="main">
//    <section className="relative overflow-hidden bg-[#06182B] text-white blueprint-dark"><div className="absolute inset-y-0 right-0 w-1/3 bg-gradient-to-l from-[#1868A8]/30 to-transparent"/><div className="relative max-w-[1160px] mx-auto px-6 py-16 sm:py-20 text-center"><p className="font-mono text-xs text-slate-300">Home › Applications › DM Plant / Demineralisation</p><p className="font-mono text-xs uppercase tracking-[.22em] text-[#E5A855] font-semibold mt-6">// Applications — Demineralisation</p><h1 className="font-serif text-5xl sm:text-6xl font-semibold mt-4">DM plant resin</h1><p className="max-w-3xl mx-auto text-slate-300 text-lg mt-5">The cation, anion and mixed bed resins that demineralise water — producing low-conductivity, high-purity water for boilers, process and high-purity duties.</p><div className="flex gap-3 justify-center flex-wrap mt-8"><Link className="bg-[#B27B34] px-6 py-3 font-semibold" to="/contact">Enquire now</Link><Link className="border border-white/40 px-6 py-3 font-semibold" to="/products">View our resins</Link></div><div className="flex flex-wrap justify-center gap-2 mt-8">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[10px] uppercase tracking-wider border border-white/20 px-3 py-2">{x}</span>)}</div></div></section>
//    <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10">
//     <div><section className="py-8"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why DM plant resin matters</h2><div className="mt-5 space-y-4 text-slate-600 leading-relaxed"><p>A demineralisation (DM) plant removes dissolved salts from water by ion exchange, producing low-conductivity, high-purity water for boilers, process and high-purity duties. Raw water carries cations (calcium, magnesium, sodium) and anions (chloride, sulphate, silica, carbon dioxide); left in, they cause scale, corrosion and off-spec product.</p><p>The DM process removes them in sequence — a strong acid cation resin takes out the cations, a strong base anion resin takes out the anions, and a mixed bed polishes the result. Toyota Chemical Industries supplies every grade in that sequence, matched to your feedwater and outlet spec, with a technical data sheet for each.</p></div></section>
//     <ImagePlaceholder />
//     <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries DM plant resin, stage by stage</h2><p className="mt-4 text-slate-600">Each stage removes a different part of the dissolved load — built from a specific AGRION grade, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
//     <ImagePlaceholder second />
//     <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">DM plant resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section></div>
//     <aside className="lg:sticky lg:top-24 space-y-5 self-start"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">DM plant resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your feedwater analysis and outlet spec — we’ll recommend the cation, anion and polishing grades and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
//     {[["Resins for this application",[["Cation Exchange Resins","/products/cation-exchange-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"],["Mixed Bed Resins","/products/mixed-bed-resins"]]],["Related applications",[["Mixed Bed / Condensate Polishing","/applications/mixed-bed-condensate-polishing"],["Dealkalisation","/applications/dealkalisation-resin"],["Boiler Feed Water","/applications/boiler-feed-water-treatment"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
//     </aside></div>
//    <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Specify the right resins for your DM plant with Toyota Chemical Industries.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your feedwater analysis and outlet spec and we’ll recommend the cation, anion and polishing grades and attach their TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
//    
//    <div className="lg:hidden fixed bottom-0 inset-x-0 z-50 bg-white border-t border-[#C8DCEC] p-2 grid grid-cols-3 gap-2"><a className="text-center border border-[#0A2C4B] text-[#0A2C4B] py-2.5 text-sm font-semibold" href="tel:+912602432021">Call</a><a className="text-center bg-[#B27B34] text-white py-2.5 text-sm font-semibold" href="https://wa.me/919898701010">WhatsApp</a><Link className="text-center bg-[#1868A8] text-white py-2.5 text-sm font-semibold" to="/contact">Enquire</Link></div>
//   </main>
//  </div>;
// }

import React from "react";
import { Link } from "react-router";
import dmPlantHeroImage from "../../assets/images/Dm plant application.jpg";
import dmPlantGenerated from "../../assets/images/application-real/appl3-1.png";
import dmPlantSupportImage from "../../assets/images/application-real/appl3-2.png";

const faqs = [["Which resins are used in a DM plant?", "A strong acid cation resin (AGRION C-100 H) for the cation stage, a Type 1 strong base anion resin (AGRION A-400) for the anion stage, and a mixed bed (AGRION MB-1151) for polishing. High-alkalinity feedwater may add a weak acid cation stage (AGRION WC-50)."], ["What is the difference between two-bed and mixed-bed demineralisation?", "A two-bed system (separate cation then anion) removes the bulk of dissolved ions; a mixed bed polishes that output to much lower conductivity and silica. High-purity duties use two-bed followed by a mixed bed. See mixed bed resins ."], ["Which anion resin removes silica in a DM plant?", "A Type 1 strong base anion resin such as AGRION A-400 — Type 1 chemistry gives the high silica and CO₂ removal that boiler-feed demineralisation needs."], ["How does dealkalisation cut my regenerant cost?", "On high-alkalinity feedwater, a weak acid cation resin (AGRION WC-50) ahead of the strong-acid bed removes alkalinity-linked hardness at high regeneration efficiency, reducing the acid demand on the downstream cation resin."], ["How do I know when to replace DM plant resin?", "Rising treated-water conductivity, earlier silica breakthrough, shorter runs between regenerations or higher regenerant use all point to exhaustion or degradation. Share your trends and we’ll advise whether a change is due."], ["Do you supply the full DM resin set from one source?", "Yes — cation, anion, mixed bed and weak acid cation grades, all manufactured by Toyota Chemical Industries, from 25 litres to bulk, each with its TDS."], ["Can AGRION DM resins replace the ones I run today?", "In most cases, yes. Match on resin type, ionic form, capacity and bead size and an AGRION grade drops into the same vessel. Send us your current grades or datasheets and we’ll confirm the equivalents."]];
const stages = [{"n": "1", "duty": "Stage 1 — Cation", "title": "Remove the cations", "tag": "The grade", "text": "A strong acid cation resin in the hydrogen form exchanges calcium, magnesium and sodium for H⁺, leaving the water acidic and cation-free.", "items": [{"text": "AGRION C-100 H"}, {"text": "Cation exchange resins", "href": "/products/cation-exchange-resins"}]}, {"n": "2", "duty": "Stage 2 — Anion", "title": "Remove the anions & silica", "tag": "The grade", "text": "A Type 1 strong base anion resin in the hydroxide form removes chloride, sulphate, silica and CO₂, neutralising the acidity and giving low-conductivity demineralised water.", "items": [{"text": "AGRION A-400"}, {"text": "Anion exchange resins", "href": "/products/anion-exchange-resins"}]}, {"n": "3", "duty": "Stage 3 — Polishing", "title": "Polish to high purity", "tag": "The grade", "text": "A mixed bed of cation and anion resin polishes the two-bed output to very low conductivity and high resistivity — for boiler feed, ultrapure and high-purity process water.", "items": [{"text": "AGRION MB-1151"}, {"text": "Mixed bed resins", "href": "/products/mixed-bed-resins"}]}, {"n": "+", "duty": "Optional — Pre-treatment", "title": "Cut regenerant cost on high-alkalinity water", "tag": "The grade", "text": "Where feedwater is high in alkalinity, a weak acid cation resin ahead of the strong-acid bed removes alkalinity-linked hardness first, cutting acid consumption and improving efficiency.", "items": [{"text": "AGRION WC-50"}, {"text": "Dealkalisation", "href": "/applications/dealkalisation-resin"}]}];
function ImagePlaceholder({ second = false }) {
  return (
    <figure className="my-8 overflow-hidden border border-[#C8DCEC] bg-[#F7FAFD] shadow-sm">
      <img src={second ? dmPlantSupportImage : dmPlantGenerated} alt={second ? "DM plant resin replacement decision flow and regeneration guidance" : "DM plant demineralisation system with cation, anion and mixed-bed stages"} loading="lazy" className="block w-full aspect-[16/9] object-cover object-center" />
    </figure>
  );
}

export default function DMPlantResin() {
 return <div className="min-h-screen bg-white text-slate-800 font-sans overflow-x-hidden">
  <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap'); .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'IBM Plex Mono',monospace} body{font-family:'Inter',sans-serif} .blueprint{background-image:linear-gradient(rgba(24,104,168,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(24,104,168,.06) 1px,transparent 1px);background-size:32px 32px} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} @media(prefers-reduced-motion:reduce){.client-track{animation:none}}`}</style>
  <main id="main">
   <section className="blueprint relative border-b border-[#C8DCEC] bg-[#F7FAFD]" style={{backgroundImage: `linear-gradient(90deg, rgba(247,250,253,1) 0%, rgba(247,250,253,.995) 28%, rgba(247,250,253,.97) 42%, rgba(247,250,253,.90) 52%, rgba(247,250,253,.70) 61%, rgba(247,250,253,.38) 70%, rgba(247,250,253,.12) 82%, rgba(247,250,253,.03) 100%), linear-gradient(180deg, rgba(247,250,253,.10) 0%, rgba(247,250,253,.16) 100%), url(${dmPlantHeroImage})`, backgroundSize: "cover", backgroundPosition: "center center", backgroundRepeat: "no-repeat"}}><div className="max-w-[1160px] mx-auto px-6 py-8 sm:py-10 lg:py-14"><p className="font-mono text-xs text-slate-500 mb-7"><Link to="/">Home</Link><span className="mx-2">›</span><Link to="/applications">Applications</Link><span className="mx-2">›</span><b className="text-[#0A2C4B]">DM Plant / Demineralisation</b></p><div className="max-w-[720px]"><p className="font-mono text-xs uppercase tracking-[.18em] text-[#B27B34] font-semibold">// Applications — Demineralisation</p><h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[#0A2C4B] leading-[1.04] mt-5 max-w-[720px] [text-shadow:0_1px_0_rgba(255,255,255,.85)]">DM plant <em className="text-[#1868A8]">resin</em></h1><p className="mt-6 max-w-[680px] text-base sm:text-lg text-[#34495E] font-medium leading-relaxed">The cation, anion and mixed bed resins that demineralise water — producing low-conductivity, high-purity water for boilers, process and high-purity duties.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/contact" className="bg-[#1868A8] text-white px-6 py-3 font-semibold text-sm hover:bg-[#0A2C4B] transition">Enquire now</Link><Link to="/products" className="border border-[#0A2C4B] text-[#0A2C4B] bg-white px-6 py-3 font-semibold text-sm hover:bg-[#EFF6FC] transition">View our resins</Link></div><div className="flex flex-wrap gap-2 mt-7">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[11px] text-[#0A2C4B] border border-[#C8DCEC] bg-white px-3 py-2">{x}</span>)}</div></div></div></section>
   <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10 lg:gap-12 items-start">
    <div className="min-w-0"><section className="pb-10"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why DM plant resin matters</h2><div className="mt-5 space-y-4 text-slate-600 leading-relaxed"><p>A demineralisation (DM) plant removes dissolved salts from water by ion exchange, producing low-conductivity, high-purity water for boilers, process and high-purity duties. Raw water carries cations (calcium, magnesium, sodium) and anions (chloride, sulphate, silica, carbon dioxide); left in, they cause scale, corrosion and off-spec product.</p><p>The DM process removes them in sequence — a strong acid cation resin takes out the cations, a strong base anion resin takes out the anions, and a mixed bed polishes the result. Toyota Chemical Industries supplies every grade in that sequence, matched to your feedwater and outlet spec, with a technical data sheet for each.</p></div></section>
    <ImagePlaceholder />
    <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries DM plant resin, stage by stage</h2><p className="mt-4 text-slate-600">Each stage removes a different part of the dissolved load — built from a specific AGRION grade, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
    <ImagePlaceholder second />
    <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">DM plant resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section></div>
    <aside className="lg:sticky lg:top-24 space-y-5"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">DM plant resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your feedwater analysis and outlet spec — we’ll recommend the cation, anion and polishing grades and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
    {[["Resins for this application",[["Cation Exchange Resins","/products/cation-exchange-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"],["Mixed Bed Resins","/products/mixed-bed-resins"]]],["Related applications",[["Mixed Bed / Condensate Polishing","/applications/mixed-bed-condensate-polishing"],["Dealkalisation","/applications/dealkalisation-resin"],["Boiler Feed Water","/applications/boiler-feed-water-treatment"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
    </aside></div>
   <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Specify the right resins for your DM plant with Toyota Chemical Industries.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your feedwater analysis and outlet spec and we’ll recommend the cation, anion and polishing grades and attach their TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
   

  </main>
 </div>;
}
