import React from "react";
import { Link } from "react-router";
import wastewaterHeroImage from "../../assets/images/ETP wastewater.jpg";
import wastewaterGenerated from "../../assets/images/application-real/ap41.png";
import wastewaterSupportImage from "../../assets/images/application-real/ap42.png";

const faqs = [["Which resins are used in effluent and wastewater treatment?", "Macroporous strong acid cation and chelating resins for heavy-metal removal and recovery, macroporous and weak base anion resins for organics and colour, and a two-bed demineraliser (AGRION C-100 H + A-400) to recover water for reuse or ZLD."], ["Which resin removes heavy metals from effluent?", "A macroporous strong acid cation resin such as AGRION C-100 MP, and where selectivity against a high sodium or calcium background is needed, a chelating resin from our specialty range that binds metals like copper, nickel, zinc and lead even at low concentration."], ["Do you supply resins for zero liquid discharge (ZLD)?", "Yes. Macroporous cation, chelating and demineralisation resins are used in ZLD and water-recovery trains to remove metals and dissolved salts so treated water can be recycled. Share your stream chemistry and we’ll advise the grades."], ["Can ion exchange recover valuable metals, not just remove them?", "Yes. Chelating and macroporous cation resins capture target metals selectively; on regeneration the metal is released in a concentrated stream, allowing recovery rather than disposal."], ["How does ion exchange help water reuse?", "After metals and organics are removed, a demineralisation stage strips the remaining dissolved salts, returning process-quality water that can be recycled into the plant instead of discharged."], ["Why macroporous resins for effluent duty?", "Effluent streams are often high in organics and prone to fouling. Macroporous grades resist organic fouling and osmotic shock and regenerate more cleanly than gel resins in these conditions."], ["Can you match the resin our ETP currently runs?", "In most cases, yes. Match on functional type, form, capacity and bead size, or share your target contaminant and current datasheet, and we’ll confirm the equivalent AGRION grade."]];
const stages = [{"n": "1", "duty": "Duty A", "title": "Remove & recover heavy metals", "tag": "The grade", "text": "A macroporous strong acid cation resin, and where selectivity against high background salinity is needed a chelating resin, removes copper, nickel, zinc, lead and similar metals from effluent — to trace levels, and for recovery.", "items": [{"text": "AGRION C-100 MP"}, {"text": "Chelating (specialty)", "href": "/products/specialty-resins"}]}, {"n": "2", "duty": "Duty B", "title": "Remove organics & colour", "tag": "The grade", "text": "Macroporous and weak base anion resins scavenge organics and colour from effluent streams, protecting downstream stages and helping meet discharge or reuse targets.", "items": [{"text": "AGRION A-650 MP"}, {"text": "AGRION A-600 MP"}, {"text": "Anion resins", "href": "/products/anion-exchange-resins"}]}, {"n": "3", "duty": "Duty C", "title": "Demineralise recovered water for reuse / ZLD", "tag": "The grade", "text": "To recycle treated water back into the process or push toward zero liquid discharge, a two-bed demineraliser strips the remaining dissolved salts — returning process-quality water from effluent.", "items": [{"text": "AGRION C-100 H"}, {"text": "AGRION A-400"}, {"text": "DM plant", "href": "/applications/dm-plant-resin"}]}];
function ImagePlaceholder({ second = false }) {
  return (
    <figure className="my-8 overflow-hidden border border-[#C8DCEC] bg-[#F7FAFD] shadow-sm">
      <img
        src={second ? wastewaterSupportImage : wastewaterGenerated}
        alt={second ? "Industrial effluent treatment and wastewater recovery equipment" : "Industrial wastewater treatment and ZLD ion exchange process"}
        loading="lazy"
        className="block w-full aspect-[16/9] object-cover object-center"
      />
    </figure>
  );
}

export default function ETPWastewaterTreatment() {
 return <div className="min-h-screen bg-white text-slate-800 font-sans overflow-x-hidden">
  <style>{`@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap');
  .font-serif{font-family:'EB Garamond',serif} .font-mono{font-family:'IBM Plex Mono',monospace} body{font-family:'Inter',sans-serif}
  .blueprint{background-image:linear-gradient(rgba(24,104,168,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(24,104,168,.06) 1px,transparent 1px);background-size:32px 32px}
  @keyframes clientScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}} .client-track{animation:clientScroll 55s linear infinite} .client-track:hover{animation-play-state:paused} @media(prefers-reduced-motion:reduce){.client-track{animation:none;flex-wrap:wrap;justify-content:center;width:auto}}
  `}</style>
  <main>
   <section className="blueprint relative border-b border-[#C8DCEC] bg-[#F7FAFD]" style={{backgroundImage: `linear-gradient(90deg, rgba(247,250,253,1) 0%, rgba(247,250,253,.995) 28%, rgba(247,250,253,.97) 42%, rgba(247,250,253,.90) 52%, rgba(247,250,253,.70) 61%, rgba(247,250,253,.38) 70%, rgba(247,250,253,.12) 82%, rgba(247,250,253,.03) 100%), linear-gradient(180deg, rgba(247,250,253,.10) 0%, rgba(247,250,253,.16) 100%), url(${wastewaterHeroImage})`, backgroundSize: "cover", backgroundPosition: "center center", backgroundRepeat: "no-repeat"}}><div className="max-w-[1160px] mx-auto px-6 py-8 sm:py-10 lg:py-14">
    <p className="font-mono text-xs text-slate-500 mb-7"><Link to="/">Home</Link><span className="mx-2">›</span><Link to="/applications">Applications</Link><span className="mx-2">›</span><b className="text-[#0A2C4B]">ETP / Wastewater Treatment</b></p>
    <div className="max-w-[720px]"><p className="font-mono text-xs uppercase tracking-[.18em] text-[#B27B34] font-semibold">// Applications — ETP / Wastewater</p><h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-[#0A2C4B] leading-[1.04] mt-5 max-w-[720px] [text-shadow:0_1px_0_rgba(255,255,255,.85)]">ETP &amp; wastewater treatment <em className="text-[#1868A8]">resin</em></h1><p className="mt-6 max-w-[680px] text-base sm:text-lg text-[#34495E] font-medium leading-relaxed">The ion exchange resins that polish effluent, remove and recover heavy metals, and recycle water for reuse and zero liquid discharge.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/contact" className="bg-[#1868A8] text-white px-6 py-3 font-semibold text-sm hover:bg-[#0A2C4B] transition">Enquire now</Link><Link to="/products" className="border border-[#0A2C4B] text-[#0A2C4B] bg-white px-6 py-3 font-semibold text-sm hover:bg-[#EFF6FC] transition">View our resins</Link></div><div className="flex flex-wrap gap-2 mt-7">{["Since 1972","ISO 9001:2015","ISO 14001:2015","TDS with every grade"].map(x=><span key={x} className="font-mono text-[11px] text-[#0A2C4B] border border-[#C8DCEC] bg-white px-3 py-2">{x}</span>)}</div></div>
   </div></section>
   <div className="max-w-[1160px] mx-auto px-6 py-10 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-10 lg:gap-12 items-start"><div className="min-w-0">
    <section className="pb-10"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// The process</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Why ETP &amp; wastewater treatment resin matters</h2><div className="mt-5 text-slate-600 leading-relaxed space-y-4"><p>Effluent treatment is no longer just about meeting a discharge limit. Plants are under pressure to remove heavy metals to trace levels, recover valuable materials, and recycle water back into the process — up to zero liquid discharge. Ion exchange does what settling and filtration cannot: it selectively removes and recovers dissolved ions, even at low concentration.</p><p>Toyota Chemical Industries supplies the macroporous, weak base and specialty grades used to polish effluent, capture heavy metals and demineralise recovered water for reuse — each with a technical data sheet.</p></div></section>
    <ImagePlaceholder />
    <section id="how" className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// How it works</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">Toyota Chemical Industries ETP &amp; wastewater treatment resin, stage by stage</h2><p className="mt-4 text-slate-600">How ion exchange fits an effluent or reuse train — built from specific AGRION grades, manufactured by Toyota Chemical Industries.</p><div className="mt-8 space-y-6">{stages.map(s=><div key={s.n+s.title} className="grid grid-cols-[44px_minmax(0,1fr)] sm:grid-cols-[58px_minmax(0,1fr)] gap-4 sm:gap-5"><div className="w-11 h-11 sm:w-[52px] sm:h-[52px] rounded-full bg-[#0A2C4B] text-white grid place-items-center font-mono font-bold shadow-lg">{s.n}</div><div className="grid md:grid-cols-[.9fr_1.15fr] border border-[#C8DCEC] bg-white shadow-sm"><div className="p-5 sm:p-6 bg-[#EFF6FC] md:border-r-4 border-[#B27B34]"><span className="font-mono text-[10px] uppercase tracking-widest bg-[#0A2C4B] text-white px-2.5 py-1">{s.duty}</span><h3 className="font-serif text-xl font-bold text-[#0A2C4B] mt-3">{s.title}</h3></div><div className="p-5 sm:p-6"><span className="font-mono text-[10px] uppercase tracking-widest text-[#B27B34] font-bold">{s.tag}</span><p className="text-sm leading-relaxed text-slate-600 mt-3">{s.text}</p><div className="flex flex-wrap gap-2 mt-4">{s.items.map((it,i)=>it.href?<a key={i} href={it.href} className="font-mono text-[11px] bg-[#F4E7D2] border border-[#B27B34] text-[#0A2C4B] px-3 py-1.5 font-semibold">{it.text}</a>:<span key={i} className="font-mono text-[11px] bg-[#F7FAFD] border border-[#C8DCEC] text-[#0A2C4B] px-3 py-1.5">{it.text}</span>)}</div></div></div></div>)}</div></section>
    <ImagePlaceholder second />
    <section className="py-12 border-t border-[#C8DCEC]"><p className="font-mono text-xs uppercase tracking-widest text-[#1868A8] font-semibold">// FAQ</p><h2 className="font-serif text-3xl sm:text-4xl text-[#0A2C4B] mt-2">ETP &amp; wastewater treatment resin — frequently asked questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="group bg-white border border-[#C8DCEC] shadow-sm"><summary className="cursor-pointer list-none px-6 py-5 flex justify-between gap-4 font-serif text-lg font-bold text-[#0A2C4B]"><span>{q}</span><span className="font-mono text-[#B27B34] group-open:rotate-45 transition">+</span></summary><p className="px-6 pb-6 pt-4 border-t border-[#EFF6FC] text-sm leading-relaxed text-slate-600">{a}</p></details>)}</div></section>
   </div>
   <aside className="lg:sticky lg:top-24 space-y-5"><div className="bg-[#06182B] text-white p-6 shadow-xl"><p className="font-mono text-[11px] uppercase tracking-widest text-[#E5A855] font-bold">ETP resin enquiry</p><p className="text-sm text-slate-300 leading-relaxed mt-3">Send your stream chemistry, target contaminant and reuse goal — we’ll recommend the grades and attach the TDS.</p><div className="grid gap-2 mt-5"><Link className="bg-[#B27B34] text-white text-center px-4 py-3 text-sm font-semibold" to="/contact">Send an enquiry</Link><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="https://wa.me/919898701010">WhatsApp us</a><a className="border border-white/40 text-white text-center px-4 py-3 text-sm" href="tel:+912602432021">Call +91 260 2432021</a></div></div>
   {[["Resins for this application",[["Cation Exchange Resins","/products/cation-exchange-resins"],["Anion Exchange Resins","/products/anion-exchange-resins"],["Specialty Resins","/products/specialty-resins"],["Mixed Bed Resins","/products/mixed-bed-resins"]]],["Related applications",[["DM Plant / Demineralisation","/applications/dm-plant-resin"],["Heavy Metal Removal / ZLD","/applications/heavy-metal-removal"],["Organic Removal","/applications/organic-removal"]]]].map(([h,items])=><div key={h} className="border border-[#C8DCEC] bg-white p-5 shadow-sm"><h4 className="font-mono text-xs uppercase tracking-widest text-[#B27B34] font-bold">{h}</h4><ul className="mt-3 divide-y divide-[#EFF6FC]">{items.map(([t,u])=><li key={t}><a className="block py-2.5 text-sm text-[#0A2C4B] hover:text-[#1868A8]" href={u}>{t}</a></li>)}</ul></div>)}
   </aside></div>
   <section className="bg-[#06182B] text-white"><div className="max-w-[1160px] mx-auto px-6 py-14 text-center"><h2 className="font-serif text-3xl sm:text-4xl max-w-3xl mx-auto">Meet discharge limits and recycle water with Toyota Chemical Industries effluent resins.</h2><p className="text-slate-300 mt-4 max-w-2xl mx-auto">Share your stream chemistry, target contaminant and reuse goal and we’ll recommend the grades and attach their TDS.</p><div className="flex flex-wrap gap-3 justify-center mt-7"><Link className="bg-[#B27B34] text-white px-6 py-3 font-semibold text-sm" to="/contact">Send an enquiry</Link><a className="border border-white/50 text-white px-6 py-3 font-semibold text-sm" href="https://wa.me/919898701010">WhatsApp us</a></div></div></section>
   
   <div className="lg:hidden fixed bottom-0 inset-x-0 z-50 bg-white border-t border-[#C8DCEC] p-2 grid grid-cols-3 gap-2"><a className="text-center border border-[#0A2C4B] text-[#0A2C4B] py-2.5 text-sm font-semibold" href="tel:+912602432021">Call</a><a className="text-center bg-[#B27B34] text-white py-2.5 text-sm font-semibold" href="https://wa.me/919898701010">WhatsApp</a><Link className="text-center bg-[#1868A8] text-white py-2.5 text-sm font-semibold" to="/contact">Enquire</Link></div>
  </main>
 </div>;
}
